(in-package #:pyx.extension)

(pyx:define-asset-pool textures (:base "data/textures")
  (brdf-lut "brdf-lut.png")
  (debug "debug.png")
  (font "font.png"))

(pyx:define-asset-pool environments (:base "data/textures/environments")
  (papermill-diffuse-back "papermill-diffuse-back.png")
  (papermill-diffuse-bottom "papermill-diffuse-bottom.png")
  (papermill-diffuse-front "papermill-diffuse-front.png")
  (papermill-diffuse-left "papermill-diffuse-left.png")
  (papermill-diffuse-right "papermill-diffuse-right.png")
  (papermill-diffuse-top "papermill-diffuse-top.png")
  (papermill-specular-back "papermill-specular-back.png")
  (papermill-specular-bottom "papermill-specular-bottom.png")
  (papermill-specular-front "papermill-specular-front.png")
  (papermill-specular-left "papermill-specular-left.png")
  (papermill-specular-right "papermill-specular-right.png")
  (papermill-specular-top "papermill-specular-top.png")
  (sky-back "sky-back.png")
  (sky-bottom "sky-bottom.png")
  (sky-front "sky-front.png")
  (sky-left "sky-left.png")
  (sky-right "sky-left.png")
  (sky-top "sky-top.png"))

(pyx:define-texture debug ()
  (:source (textures debug)))

(pyx:define-texture brdf-lut ()
  (:source (textures brdf-lut)))

(pyx:define-texture font ()
  (:source (textures font)))

(pyx:define-texture papermill-diffuse (:cube-map)
  (:source (:x+ (environments papermill-diffuse-right)
            :x- (environments papermill-diffuse-left)
            :y+ (environments papermill-diffuse-bottom)
            :y- (environments papermill-diffuse-top)
            :z+ (environments papermill-diffuse-front)
            :z- (environments papermill-diffuse-back))))

(pyx:define-texture papermill-specular (:cube-map)
  (:min-filter :linear-mipmap-linear
   :source (:x+ (environments papermill-specular-right)
            :x- (environments papermill-specular-left)
            :y+ (environments papermill-specular-bottom)
            :y- (environments papermill-specular-top)
            :z+ (environments papermill-specular-front)
            :z- (environments papermill-specular-back))))

(pyx:define-texture sky (:cube-map)
  (:source (:x+ (environments sky-right)
            :x- (environments sky-left)
            :y+ (environments sky-bottom)
            :y- (environments sky-top)
            :z+ (environments sky-front)
            :z- (environments sky-back))))
