(in-package #:%pyx.metadata)

(glob:define-global-var =animation-states= (u:dict #'eq))
(glob:define-global-var =animation-sequences= (u:dict #'eq))
(glob:define-global-var =asset-dependencies= (u:dict #'eq))
(glob:define-global-var =asset-pools= (u:dict #'eq))
(glob:define-global-var =collider-plans= (u:dict #'eq))
(glob:define-global-var =framebuffers= (u:dict #'eq))
(glob:define-global-var =geometry= (u:dict #'eq))
(glob:define-global-var =geometry-layouts= (u:dict #'eq))
(glob:define-global-var =materials= (u:dict #'eq))
(glob:define-global-var =render-passes= (u:dict #'eq))
(glob:define-global-var =prefabs= (u:dict #'eq))
(glob:define-global-var =scenes= (u:dict #'eq))
(glob:define-global-var =textures= (u:dict #'eq))
(glob:define-global-var =viewports= (u:dict #'eq))
