(in-package #:ndjinn)

(glob:define-global-var =meta/asset-pools= (u:dict #'eq))
(glob:define-global-var =meta/collision-plans= (u:dict #'eq))
(glob:define-global-var =meta/component-order= (u:dict #'eq))
(glob:define-global-var =meta/component-args= (u:dict #'eq))
(glob:define-global-var =meta/component-static= nil)
(glob:define-global-var =meta/config-developer= (u:dict #'eq))
(glob:define-global-var =meta/config-player= (u:dict #'eq))
(glob:define-global-var =meta/contexts= (u:dict #'eq))
(glob:define-global-var =meta/curves= (u:dict #'eq))
(glob:define-global-var =meta/entity-mixins= (u:dict #'equal))
(glob:define-global-var =meta/framebuffers= (u:dict #'eq))
(glob:define-global-var =meta/geometry= (u:dict #'eq))
(glob:define-global-var =meta/geometry-layouts= (u:dict #'eq))
(glob:define-global-var =meta/materials= (u:dict #'eq))
(glob:define-global-var =meta/prefabs= (u:dict #'eq))
(glob:define-global-var =meta/render-passes= (u:dict #'eq))
(glob:define-global-var =meta/scenes= (u:dict #'eq))
(glob:define-global-var =meta/textures= (u:dict #'eq))
(glob:define-global-var =meta/viewports= (u:dict #'eq))
